class_name DecisionRouter
extends RefCounted

const DecisionCandidate = preload("res://src/domain/cognition/decision_candidate.gd")
const DecisionSelectionResult = preload("res://src/domain/cognition/decision_selection_result.gd")

## Pure competition/routing service. It selects only among candidates already
## generated by Wilson-relative producers. Hidden World truth is not consulted here.

func resolve(candidates: Array, current_intention = null):
	var threats := _scope_candidates(candidates, DecisionCandidate.Scope.IMMEDIATE_THREAT)
	if not threats.is_empty():
		return _select(threats, &"immediate_threat")

	if current_intention != null:
		var tactical := _scope_candidates(candidates, DecisionCandidate.Scope.TACTICAL)
		if not tactical.is_empty():
			return _select(tactical, &"tactical")

	var intentional := _scope_candidates(candidates, DecisionCandidate.Scope.INTENTIONAL)
	if not intentional.is_empty():
		return _select(intentional, &"intentional")

	return DecisionSelectionResult.new(null, &"none", ["No candidate available for active decision regime"])

func _scope_candidates(candidates: Array, scope: int) -> Array:
	var result: Array = []
	for candidate in candidates:
		if candidate != null and candidate.scope == scope:
			result.append(candidate)
	return result

func _select(candidates: Array, regime: StringName):
	var ordered := candidates.duplicate()
	ordered.sort_custom(_candidate_less)
	var selected = ordered[0]
	return DecisionSelectionResult.new(
		selected,
		regime,
		[
			"Selected %s score=%.4f regime=%s" % [selected.stable_key(), selected.total_score(), String(regime)],
			"Candidate count=%d" % ordered.size(),
		]
	)

func _candidate_less(a, b) -> bool:
	var score_a: float = a.total_score()
	var score_b: float = b.total_score()
	if not is_equal_approx(score_a, score_b):
		return score_a > score_b
	return a.stable_key() < b.stable_key()
